runtime: nodejs16

instance_class: F2

env_variables: 
  BUCKET_NAME: "bucket"

handlers:
- url: /
  static_files: dist/angular6-springboot-client/index.html
  upload: dist/angular6-springboot-client/index.html

- url: /
  static_dir: dist/angular6-springboot-client